### ISSUE TITLE
Apple Mach-O linker error

### ISSUE THREAD

**Issue by deepak2008** [alexleutgoeb/ALToastView#4]
I imported the Quratzcore framework, #import ed your ALToastView.h and added this line, [ALToastView toastInView:self.view withText:@"Invalid Code"]; and I got the error when I tried to build in xcode 4.6

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_ALToastView", referenced from:
      objc-class-ref in ScanViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by alexleutgoeb** [comment]
Sure you added the ALToastView.m file to your _Compile Sources_ build phase in your active target?

![test xcodeproj](https://f.cloud.github.com/assets/143259/1064206/9aef87a4-131a-11e3-8d88-413ed5101c30.png)

**Comment by deepak2008** [comment]
Thanks Alex, that worked.
Now I am facing one different issue. I want to send .ipa file to my friend in other country just to check the app if its working properly or not. Here's what I did.
1. I downloaded .cer (certificate) and added the app in identifiers for generating app id.
2. I selected Ad-HOC in Distribution section of Provisioning profile, selected the app id with my app's bundle identifier and download .mobileprovision file.
3. I double clicked the .mobileprovision file and in Build Settings (Code Signing) I selected "developer" in "debug" and "distribution" in "Realease" section of code signing identity.
4. Build & Archived and sent the ipa file which is not getting installed in my friend's device.

Do I have to send the .cer file also? But, it does not work.

I tried testflightapp.com, but when I upload the .ipa file, I get issue as mentioned in the link which is not helpful. http://developer.appcelerator.com/question/123305/help-with-testflightapp

**Comment by alexleutgoeb** [comment]
You probably forgot to add your friend's device to your ad hoc provision profile, but this is far beyond the kind of support you can expect at github open source repos, I would suggest you better post your question on stackoverflow if google doesn't help.
